### ISSUE TITLE
Support for other rule types

### ISSUE THREAD

**Issue by f-bader** [f-bader/SentinelARConverter#12]
### Summary of the new feature / enhancement

Add support for 
[ ] Fusion
[ ] NRT
[ ] ML
[ ] Threat Intelligence
[ ] Microsoft Security 

### Proposed technical implementation details (optional)

Based on YAML or ARM template rule detection

**Comment by Manbearpiet** [comment]
Can we perhaps agree on some sort of documented format on how to store these as YAML?
Will everything be a top level property? Will all properties always be available, what's the minimum and what is an extensive example?

- Fusion example?
- [NRT example](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Azure%20Active%20Directory/Analytic%20Rules/NRT_ADFSDomainTrustMods.yaml)
- ML example?
- Threat Intelligence example?
- Microsoft Security example?

**Comment by f-bader** [comment]
Definitely. I will create some extensive YAML files that we can use for validation purposes

**Comment by f-bader** [comment]
The first two examples

* [Scheduled example](https://github.com/f-bader/SentinelARConverter/blob/68a3cd00ac2f1844e73113424948f6db9a612678/tests/examples/ExampleQueryWithAllPossibleSettingsScheduled.yaml)
* [NRT example](https://github.com/f-bader/SentinelARConverter/blob/68a3cd00ac2f1844e73113424948f6db9a612678/tests/examples/ExampleQueryWithAllPossibleSettingsNRT.yaml)

**Comment by f-bader** [comment]
Basically we should implement a 1:1 version of the ARM template converted to YAML with the following changes:
* Reorder the YAML for better readability
* Rename the following parameters to match [Sentinel YAML format](https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide)
  * `displayName` = `name`
  * `alertRuleTemplateName` = `id`
  * `templateVersion` = `version`
  * `techniques` = `relevantTechniques`
* Change `triggerOperator` to match YAML
  * `Equals` = `eq`
  * `GreaterThan` = `gt`
  * `GreaterThanOrEqual` = `ge`
  * `LessThan` = `lt`
  * `LessThanOrEqual` = `le`

[Microsoft.SecurityInsights alertRules](https://learn.microsoft.com/en-us/azure/templates/microsoft.securityinsights/alertrules?pivots=deployment-language-arm-template)

## Scheduled

```yaml
alertDetailsOverride:
  alertDescriptionFormat: string
  alertDisplayNameFormat: string
  alertDynamicProperties:
  - alertProperty: string
    value: string
  alertSeverityColumnName: string
  alertTacticsColumnName: string
id: string
customDetails: {}
description: string
name: string
enabled: bool
entityMappings:
- entityType: string
  fieldMappings:
  - columnName: string
    identifier: string
eventGroupingSettings:
  aggregationKind: string
incidentConfiguration:
  createIncident: bool
  groupingConfiguration:
    enabled: bool
    groupByAlertDetails:
    - string
    groupByCustomDetails:
    - string
    groupByEntities:
    - string
    lookbackDuration: string
    matchingMethod: string
    reopenClosedIncident: bool
query: string
queryFrequency: string
queryPeriod: string
sentinelEntitiesMappings:
- columnName: string
severity: string
suppressionDuration: string
suppressionEnabled: bool
tactics:
- string
relevantTechniques:
- string
version: string
triggerOperator: string
triggerThreshold: int
```
